// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"init","status":true,"description":"","parameters":{}},
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"requests","status":true,"description":"","parameters":{}},
{"name":"utils","status":true,"description":"","parameters":{}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"CmdInp","status":true,"description":"","parameters":{}},
{"name":"GALV_EventSpawner","status":true,"description":"(v.1.8) Spawn events from a specified spawn map to a desired location.","parameters":{"Spawn Map Id":"6"}},
{"name":"engine","status":true,"description":"","parameters":{}},
{"name":"Subscription","status":true,"description":"","parameters":{}},
{"name":"EventWrapper","status":false,"description":"A simple wrapper for creating and handling events in your plugins. Press Help to see usage info.","parameters":{}}
];
